### ISSUE TITLE
Support plugin caddy-tlsconsul 

### ISSUE THREAD

**Issue by smilelikeshit** [caddyserver/ingress#108]
hello team. 
how to integrate with this plugin https://github.com/pteich/caddy-tlsconsul ?

**Comment by Embraser01** [comment]
Hi, for now, you'd have to create a new middleware like this one https://github.com/caddyserver/ingress/blob/master/internal/caddy/global/secrets_store.go that would overwrite the default way it works

**Comment by smilelikeshit** [comment]
thank you @Embraser01  😁
