### ISSUE TITLE
Support specyfing loadBalancerIP

### ISSUE THREAD

**Issue by Morishiri** [caddyserver/ingress#109]
In production environments you usually don't want your IPs to be dynamic (e.g. in a case of redeployment) and you want to specify (previously obtained) IP address for ingress controller load balancer service.

To do so, it is enough to specify `.spec.loadBalancerIP` in controller `service`. (Example in ingress-nginx: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-service.yaml#L25-L27)

**Comment by cobraz** [comment]
This is solved with https://github.com/caddyserver/ingress/pull/111.

**Comment by BartTactick** [comment]
@simenandre how can i use this?

**Comment by Embraser01** [comment]
The fix has been released in Chart v1.0.5 / Docker Image v0.1.5

Sorry for the delay
