### ISSUE TITLE
How can I use Caddy's DNS providers? 

### ISSUE THREAD

**Issue by Xinayder** [caddyserver/ingress#130]
I've posted this question on the Caddy forums and I'm posting it here as well:

I am fiddling around with installing a small k8s cluster using k3s and I right now I have all of my services running standalone in a single VPS. I would like to move those to a k8s cluster.

Right now, my setup consists of the services running on the VPS and Caddy acting both as a reverse proxy and as the web server for my personal website. If I want to move it to a containerized solution, it would be nice to have a service or app that will automatically add/remove new reverse proxy entries on the Caddyfile and reload Caddy; that way I can easily add new services to my server without worrying about manually setting them up. I know something similar exists for nginx and I was planning on coding my own solution just for practice.

I then changed my mind and decided to go with a K8s instead. I found out that there’s this WIP Ingress controller for Caddy. At a first glance it seems like it acts both as a load balancer and reverse proxy.

I was checking the examples and I couldn’t find anything related to how the SSL certificates are obtained or if it’s just issuing certificates for localhost domains. How is Caddy creating certificates for custom domains? I couldn’t find any reference to the DNS provider APIs on the repository.

My questions are:

- Is it possible to pack the controller together with any of the DNS provider plugins?
- If I want to serve content from my k8s to the internet, using my custom domain, what do I need to setup other than to the config file to use my domain?
- Is the ingress controller working as a reverse proxy as well or is it just a load balancer for now?
- In my use case, do I need to have 2 instances of Caddy, so that I can install the DNS plugin to the instance handling the certificates for my domain?

**Comment by Embraser01** [comment]
> Is it possible to pack the controller together with any of the DNS provider plugins?

Yes and no. You'll have to edit the code to add the wanted DNS provider and probably change the code to configure the DNS as an issuer. Note that without additional plugins, the ingress controller can issue certificates with any ACME endpoint (Let's Encrypt, ZeroSSL, ...)

> If I want to serve content from my k8s to the internet, using my custom domain, what do I need to setup other than to the config file to use my domain?

You'll have to deploy this controller (using the Helm Chart for simplicity), and create an [Ingres](https://kubernetes.io/docs/concepts/services-networking/ingress/) object for each service you want to expose.
Other than that, you'll need to create DNS records on your domain provider to point to your k8s cluster.

> Is the ingress controller working as a reverse proxy as well or is it just a load balancer for now?

This controller will act primarily as a reverse proxy. The Load balancing will be done directly by k8s-proxy (on each node). It means that for now, load balancing rules in caddy can't be used in this controller

> In my use case, do I need to have 2 instances of Caddy, so that I can install the DNS plugin to the instance handling the certificates for my domain?

The controller can be parallelized on k8s for redundancy, they will share their config and can work together to issue new certificates

**Comment by Xinayder** [comment]
Thank you for the answers.

> Yes and no. You'll have to edit the code to add the wanted DNS provider and probably change the code to configure the DNS as an issuer. Note that without additional plugins, the ingress controller can issue certificates with any ACME endpoint (Let's Encrypt, ZeroSSL, ...)

It should also be possible to use cert-manager with any ingress controller, right? In this case cert-manager will issue the certificates and the ingress controller can just use an existing certificate, correct?

**Comment by Xinayder** [comment]
> This controller will act primarily as a reverse proxy. The Load balancing will be done directly by k8s-proxy (on each node). It means that for now, load balancing rules in caddy can't be used in this controller

Is it possible to have a custom Caddyfile or have it host a website as well, or I would need to have a separate Caddy pod serving my website and use the Ingress controller to act as the reverse proxy for it?

**Comment by Xinayder** [comment]
FYI, if someone wants to use DNS-01 challenge with this ingress controller, take a look at cert-manager. I added it to my setup, my DNS is managed by Vultr and there's a webhook package for cert-manager that interacts with the Vultr API to add a DNS zone to the domain. So, in the end, cert-manager is responsible for issuing the certificates and the ingress controller can use them.
