### ISSUE TITLE
We need a CI / Build server

### ISSUE THREAD

**Issue by dannav** [caddyserver/ingress#14]
We also want to start implementing some tests for this

**Comment by charles-d-burton** [comment]
Would Github actions fit the bill?  I can get that setup and PR'd to you.

**Comment by mholt** [comment]
@charles-d-burton I don't have enough experience with Kubernetes to know for sure, but I'd be happy to get you what you need in order to set up Actions. Just tell me what you need!

**Comment by mavimo** [comment]
@charles-d-burton there is kind action that can be used to setup a ephemeral cluster to use for testing purpose, see https://github.com/marketplace/actions/kind-kubernetes-in-docker-action

**Comment by charles-d-burton** [comment]
Cool, I have a good bit on my plate through next Monday but I'll be freed up a bit after that and I'll get the build portion PR'd to you as soon as I can.  Deployment CI will be a bit harder but I'll happily have that discussion once I get past the build artifact generation.

**Comment by mavimo** [comment]
@dannav @charles-d-burton @mholt I think we can consider this task completed, I'm going to close it, feel free to re-open or create a new issue if something is missing :)
