### ISSUE TITLE
Can't pull ingresscontroller image from GCR

### ISSUE THREAD

**Issue by alexanderreno** [caddyserver/ingress#17]
After applying and running the standard 
`helm template \
    --namespace=caddy-system ./kubernetes/helm/caddyingresscontroller/ \
    --set autotls=true \
    --set email="myemail" | kubectl apply -f -`
I am getting an error in kubernetes telling me "Cannot pull image 'gcr.io/danny-239313/ingresscontroller:v0.1.0' from the registry.
Check Pod's events to see more details"

Running a describe pod gives me these results:

![Screen Shot 2019-11-08 at 3 28 42 PM](https://user-images.githubusercontent.com/53441526/68514936-74420b00-023c-11ea-9dd0-8f59fb0cf8f2.png)

**Comment by dannav** [comment]
You'll want to build the docker image and host it in your own container registry and reference that

**Comment by riker09** [comment]
I have created a PR #22 that will help building a Docker image.

**Comment by eriklott** [comment]
Is there a technical reason why the caddy ingress image is not publicly available? We were also unable to pull the 'gcr.io/danny-239313/ingresscontroller:v0.1.0' image used in the Helm chart. To use this ingress (which is great by the way) we had to fork the project, re-write the Dockerfile as per @riker09 's PR, write a build script, and then customize the Helm chart to use our custom image. Seems like a lot of hoops to jump through, when this could all be avoided by hosting the image publicly. Thoughts?

**Comment by mholt** [comment]
@eriklott 

>  there a technical reason why the caddy ingress image is not publicly available?

Because it doesn't work / isn't finished, maybe? We would love it if the community could step up to help finish and maintain it!

**Comment by eriklott** [comment]
Thanks for getting back @mholt. Entirely my mistake; I didn't realize this was a work in progress. I'd be happy to contribute if I get to the point where I understand the kubernetes internals a little better as well.

Thanks again for creating Caddy. Amazing piece of work.

**Comment by riker09** [comment]
I totally agree with @eriklott, Caddy is just magnificent. I'm already watching this repository very closely and I'm eager for Caddy v2. However, I don't have the skills (read: experience) with Kubernetes to maintain an IngressController resource. Let alone the time :sweat_smile: 

I have updated the Dockerfile in my patch so that the PR can be merged.

**Comment by mavimo** [comment]
@alexanderreno the image is now available here https://hub.docker.com/r/caddy/ingress feel free to close this issue :)
