### ISSUE TITLE
How to get Client IP?

### ISSUE THREAD

**Issue by gnasnik** [caddyserver/ingress#176]
First of all, thank you for such a great project. I replaced ngnix-ingress with caddy-ingress in order to be able to automatically register the certificate. This is all great, but my usage scenario requires obtaining the ClientIP, but I did not find the relevant documentation. Did I miss something?

**Comment by mavimo** [comment]
@gnasnik if you enable the proxy pass in the load balancer (depending from the cloud provider this can be done via annotation or ..) you will get the Client IP properly

**Comment by clems71** [comment]
I had the same problem, and if your cloud provider does not support PROXY protocol, you can use what I introduced recently: https://github.com/caddyserver/ingress/pull/168 (works fine with Azure AKS)

**Comment by mavimo** [comment]
@clems71 NB: your PR is merged but we still need to release the last version of the chart, will be available soon ;)

**Comment by mavimo** [comment]
Helm chart is released (and also include the new version of the Caddy Ingress controller), now both PROXY PASS and ClientIP are available 😄
