### ISSUE TITLE
How to use caddy with AWS Certificate Manager ?

### ISSUE THREAD

**Issue by davidt-gh** [caddyserver/ingress#247]
I'm having a new EKS cluster, my old env is ECS that each one have ALB, but everyone use the same certificate which configured in [AWS Certificate Manager](https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/welcome)
I want to use that certificate by provided ARN, is that possible? Or provide a wildcard for a specific domain name using the same certificate? and all ingresses will inherit annotation from this configuration?

**Comment by mavimo** [comment]
@davidt-gh this is not possible at the moment, if you want to contribute I'll be happy to support you :)

**Comment by davidt-gh** [comment]
> and

For now I'll try to use cert-manager to generate to certificate, and use it.
Thank you for let me know.
