### ISSUE TITLE
extensions/v1beta1 API deprecated in kubernetes >1.16

### ISSUE THREAD

**Issue by rajasiman** [caddyserver/ingress#34]
### INFO
---

According to the [documentation](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/), `apiVersion: apps/v1` should be used instead of `extensions/v1beta1`

The helm chart deployment failed without doing this change, FYI.

Change to be done at `./kubernetes/helm/caddyingresscontroller/templatestemplates/deployment.yaml`

**Comment by Embraser01** [comment]
Hi,

We are currently working on a new Helm chart at #24 where we will be removing any deprecated api.

> Note that this is still a Work In Progess and a lot of things are not ready yet. I'll try to continue working on it in the next weeks

**Comment by mavimo** [comment]
@rajasiman the new chart is now merged on master, I'm going to close this issue, feel free to re-open if you think something is missing, thx!

**Comment by rajasiman** [comment]
I am going to test it and give you guys more feedback :) Glad to be of help.
