### ISSUE TITLE
Kuberntes configurations files instead of helm

### ISSUE THREAD

**Issue by Kiura** [caddyserver/ingress#41]
Is there a plan to add documentation on how to setup caddy for those who don't use helm?
kubernetes configuration or kustomize would be nice to have.

it is fairly easy to start using Nginx https://kubernetes.github.io/ingress-nginx/deploy/#gce-gke just fetching the config files and applying them. It would be nice to have something similar to this in caddy or even better to have a kustomize for greater control over the deployment

**Comment by hairyhenderson** [comment]
In theory it could be pretty easy to generate straight Kubernetes resources by simply running the [`helm template`](https://helm.sh/docs/helm/helm_template/) command.

**Comment by Kiura** [comment]
hmm, thank you, completely forgot about this feature of helm, might be useful to update the documentation to reflect this for those who are not very familiar with helm

**Comment by hairyhenderson** [comment]
@Kiura That sounds like a good idea! Would you be willing to submit a PR with that addition?

**Comment by yunfan** [comment]
@Kiura  can you paste a kubernetes yaml here? i havnt use helm before

**Comment by eliasp** [comment]
[PR#42 adds instructions](https://github.com/caddyserver/ingress/pull/42/files) how to generate K8S YAML using `helm template`.
