### ISSUE TITLE
Cannot install using Helm - chart not found

### ISSUE THREAD

**Issue by olliephillips** [caddyserver/ingress#44]
Trying to set this up, but can't install it. 

Installed Helm, created the namespace, then tried  `helm install` using the command in the README (below):

```
helm install \
    --namespace=caddy-system \
    --repo https://caddyserver.github.io/ingress/ \
    --atomic \
    --set image.tag=latest \
    mycaddy \
    caddy-ingress-controller
```

I get this error:

```
Error: chart "caddy-ingress-controller" not found in https://caddyserver.github.io/ingress/ repository
```

I'm running on a local cluster.
Helm version is: `version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`

**Comment by mavimo** [comment]
@olliephillips you need to use the `--devel` flag since we not released only the RC version...

**Comment by olliephillips** [comment]
That fixes it. I have other problems but unrelated to this issue. Closing it. Thank you!
