### ISSUE TITLE
Caddy plugin support

### ISSUE THREAD

**Issue by silverbackdan** [caddyserver/ingress#52]
I'm sorry for the newbie issue here. I'm hoping to include Caddy ingress with a plugin for Vulcain which has been created. See: https://github.com/dunglas/vulcain/blob/master/docs/caddy.md

I'm sure there are many plugins for Caddy which is one of the great things about it - is there an easy way to use this ingress with additional plugins? If so, it'd be great to see some info in the documentation about it and I'd be using this right away. If not, is it a feature worth considering having the ability to add in or have docs about how one may do this (perhaps creating a new Docker image and basing it on the image here with a small example as a starting point?)

Thanks in advance.

**Comment by Embraser01** [comment]
Hi :wave:
For now, there isn't a easy way to add plugins in the controller. I don't think it will be added in the foreseeable future.

For you use case: I don't know Vulcain but I think it should be put behind the Caddy Ingress Controller as a Kubernetes Deployment & Service instead of integrating it in the Caddy Ingress process

**Comment by dunglas** [comment]
Regarding Vulcain, it must be at the edge because it trigger HTTP/2 Server Pushes. The Ingress looks like the right place for this module if you use Server Push. If you use preload hints, a standard deployment is ok.

**Comment by silverbackdan** [comment]
Thank you both for your replies!

Ah ok, so I can create a vulcain service and still get some speed benefits using preload headers? Am I right in thinking that Chrome was deprecating push support as well? The ability to receive resolved requests simultaneously was going to be a big improvement for an application of mine, but if the browser won't support it, not much we can do. If I'm wrong regarding push support deprecation then figuring out how to get vulcain on the edge would be great, but I will get in touch with your company about that when the time is right in my project.

**Comment by dunglas** [comment]
@silverbackdan yes and yes, see https://twitter.com/dunglas/status/1326552735404060672?s=21.

We're going to make some announcements about Vulcain soon, basically we'll recommend to use preload hints when targeting Chrome.

**Comment by silverbackdan** [comment]
Thank you. In which case I had some helm templates which was implementing Vulcain as a service which I'll re-introduce. Fingers crossed for the early hints support. Closing the issue here as it's getting off topic for this repo.
