### ISSUE TITLE
Is this production ready? Is anyone using it in production?

### ISSUE THREAD

**Issue by JCMais** [caddyserver/ingress#56]
Title. I am thinking about using this, but if it's not ready for production use yet I will search for something else.

**Comment by Embraser01** [comment]
Hi, the project is not production ready yet. There is still a lot of features and testing to do before being there (OnDemandTLS, Annotations config,...).

Currently, it works at a small scale and without too much interferences.

**Comment by Embraser01** [comment]
You can deploy caddy as a simple deployment (replica: 1) using the caddy docker image. You'll be able to sepcify the config but you'll not be able to use the `Ingress` K8S object.

Links:
- Caddy migration from v1 https://caddyserver.com/docs/v2-upgrade
- Caddy docker image https://hub.docker.com/_/caddy

**Comment by JCMais** [comment]
Thanks @Embraser01
