### ISSUE TITLE
caddy ingress controller clusterrole is missing configmap resource access

### ISSUE THREAD

**Issue by sgtsquiggs** [caddyserver/ingress#62]
`- configmap` should be appended below

https://github.com/caddyserver/ingress/blob/66c52c682f497022f43ffb529def89c3a8ff3472/charts/caddy-ingress-controller/templates/clusterrole.yaml#L18-L23

**Comment by Embraser01** [comment]
PR #60 has the needed [fix](https://github.com/caddyserver/ingress/pull/60/files?file-filters%5B%5D=.yaml#diff-f590d1f475a7a046e551ed93d594bd1c41dd351b52c4513127c35a4b074a2de0R26) for this.

I need to get back to it (I hope before Christmas 😃)
