### ISSUE TITLE
helm can't find chart

### ISSUE THREAD

**Issue by kmpm** [caddyserver/ingress#71]
Helm can not find the caddy-ingress-controller chart

    $ helm repo add caddyserver https://caddyserver.github.io/ingress/

    $ helm repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Successfully got an update from the "caddyserver" chart repository
    Update Complete. ⎈ Happy Helming!⎈
    
    $ helm pull caddyserver/caddy-ingress-controller
    Error: chart "caddy-ingress-controller" matching  not found in caddyserver index. (try 'helm repo update'): no chart version found for caddy-ingress-controller-

    $ helm version
    version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

It shouldn't matter but this is in PowerShell on a Windows 10 Pro 64-bit machine.

**Comment by VinGarcia** [comment]
This looks like the same issue reported on #73.

I was able to build it the chart locally and then install it, (I documented how I did it on #73) if this is not going to be fixed then we should change the instructions on how to install this project.
