### ISSUE TITLE
Spinning startup

### ISSUE THREAD

**Issue by acky666** [caddyserver/ingress#79]
Hiya,

Using Caddy on K8's ( Client: 1.22.4  Server: 1.21.5 ).  When deploying to the cluster the caddy pod, spins every minute with these messages.  I can't for the life of me see where the resource name might be"  I have looked through the code and can't see any error lines with the caddy config reload: prefix.

Does anyone know what this error refers to? 

time="2022-01-03T13:58:55Z" level=info msg="Found TLS certificates on ingress resource. Syncing..."
time="2022-01-03T13:58:55Z" level=error msg="caddy config reload: resource name may not be empty"
time="2022-01-03T13:58:55Z" level=info msg="Ingress resource update detected, updating Caddy config..."
time="2022-01-03T13:58:55Z" level=info msg="Updating caddy config"
time="2022-01-03T13:58:55Z" level=info msg="using config map options: map[**redacted**]"

Thanks.

**Comment by acky666** [comment]
This is solved.    Needed to use apiVersion  networking.k8s.io/v1beta1 on the ingress.     The service name and port are different on the networking.k8s.io/v1 API.   Since the beta1 is going to deprecated in 1.22.   I think this needs updating.     

(internal / caddy / ingress)  line 43.   Probably to handle both APIs.

**Comment by malthe** [comment]
Bump?

@Embraser01 gentle ping ...
