### ISSUE TITLE
remote error: tls: internal error

### ISSUE THREAD

**Issue by sebastian-philipp** [caddyserver/ingress#97]
Hi, I'm getting an internal tls error when setting up the ingress controller:
```
{
  "level": "info",
  "ts": 1660570677.2124605,
  "logger": "tls.issuance.acme.acme_client",
  "msg": "trying to solve challenge",
  "identifier": "dev.portal.as5405.net",
  "challenge_type": "tls-alpn-01",
  "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"
}
{
  "level": "info",
  "ts": 1660570677.783701,
  "logger": "tls",
  "msg": "served key authentication certificate",
  "server_name": "dev.portal.as5405.net",
  "challenge": "tls-alpn-01",
  "remote": "10.2.0.0:47421",
  "distributed": false
}
{
  "level": "error",
  "ts": 1660570678.1925125,
  "logger": "tls.issuance.acme.acme_client",
  "msg": "challenge failed",
  "identifier": "dev.portal.as5405.net",
  "challenge_type": "tls-alpn-01",
  "problem": {
    "type": "urn:ietf:params:acme:error:tls",
    "title": "",
    "detail": "51.91.26.152: remote error: tls: internal error",
    "instance": "",
    "subproblems": []
  }
}
...
{
  "level": "error",
  "ts": 1660570680.495199,
  "logger": "tls.issuance.acme.acme_client",
  "msg": "challenge failed",
  "identifier": "dev.portal.as5405.net",
  "challenge_type": "http-01",
  "problem": {
    "type": "urn:ietf:params:acme:error:tls",
    "title": "",
    "detail": "During secondary validation: 51.91.26.152: Fetching https://dev.portal.as5405.net/.well-known/acme-challenge/mhyCAzif10cHjvMsHeT4yLmvaJ9omUHQnXmsoNoQ-w0: remote error: tls: internal error",
    "instance": "",
    "subproblems": []
  }
}
```
Looks like it's impossible to get solve the challenge due to the tls error. The ingress is pretty much standard without any fancy setup. Would be great, if we could fix this automatically. 

workaround: delete the pods

**Comment by Embraser01** [comment]
Hi,

I'm not sure on what is happening here without more info on how it's setup. What load balancer is in front of the caddy ingress controller? What does the caddy configmap look like? 
Can you provide the full JSON config used by caddy (should be logged on startup)

**Comment by sebastian-philipp** [comment]
I'm using OVH's load balancer. But Unfortunately it works by now. I'd be ok with closing it.

**Comment by Embraser01** [comment]
I'm gonna close it for now, but feel free to reopen it if you find more debugging information. 
Note that it may be related to OVH's load balancer (I'm not familiar with it) having trouble to keep ingress controller pods in sync, for example AWS takes ~2min to let a pod available on their network load balancer.

**Comment by felipecrs** [comment]
I found the same problem in a GKE Autopilot cluster. And deleting the caddy pods indeed solve the issue. :)
